version: '3.5'

services:
  homer:
    image: homer-the-simp/homer:1.0
    security_opt:
      - apparmor:unconfined
      - seccomp:./profile.json
    cap_add:
      - SYS_ADMIN
    ports:
      - '2222:22'
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.2'
          memory: 100m
  marge:
    image: homer-the-simp/marge:1.0
    security_opt:
      - seccomp:./profile.json
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.2'
          memory: 100m
