version: '3.5'

services:
  homer:
    image: homer-the-simp/homer:1.0
    ports:
      - '2222:22'
    deploy:
      replicas: 6
      resources:
        limits:
          cpus: '0.2'
          memory: 100m
  marge:
    image: homer-the-simp/marge:1.0
    deploy:
      replicas: 6
      resources:
        limits:
          cpus: '0.2'
          memory: 100m
